language: node_js
node_js:
- 4.2.3
matrix:
  fast_finish: true
  allow_failures:
  - node_js: 5.1.1
before_script:
- npm install -g bower grunt-cli
- bower install
services: mongodb
before_deploy:
- grunt build
- ls -ltra
deploy:
  app: acc-bbq
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: hFbTuOcTP+yQTmvGuMDnYE2OeaCpQ8bfqxIaO91OTdlN/pTvcljc1sYtRJZBAlcUyCl7Z44vRCQVOZLDZm3jQAd53eJmDFNYtcD1S1vLU5Kukj6F30wMAk5vpZwFXlcmnRxv4mBuzG7XY9F55G+xZFXYRRSwvLlaor0trGb4mgdDzymQlVEQLlt9A2sFGCTrbaf1+WHChDUjdqpsfjfUI/lWWwbrHzPM4NG4xIysAs8/vqIG1D3BU5NLeOuhB+OiP/Sv8A0/lclJpLlb/c0e4ak7JA4lQjP8whOOH6cch3x4zHfp+eoUT6BEDklZT8ojUqddisHdTDhVWa+FoM256A6HVu9TLUa+lVs1T9FQyjLiXnsTLuEP7wY1pP1+uPeFWwgGRf24WihYbO1DUbsgrOgggx5uebBkYXDcUMvOjXG09EM61DLFs1KYiV7xC98G8FfS/8ZQIEPyNLqiwXx8tysQm+J64GkHhiKSKbIaGmHABor39Vb5cXdbb8RMMUHwFAt+tZNsHA5YdVTRIVSykmNNpVMMjQ44NrgQugtmR0VtKl7NlsAGwHvSX3lFCNGACKqJpwVKsn3qulLLeUNmHMM4Rap7NVae/FPe6k/7ufXvmIV1BypEnQ13ML4oGuSNU15aMSCNCNbgk72yvpd+knM/yEwtzi4++EnK7x9yrLM=
cache:
  directories:
  - node_modules
